"""add content_hash column to documents for cross-run dedup

Revision ID: 86bedb422f4b
Revises: 23c14cd0373a
Create Date: 2026-09-03 01:32:43.951328

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86bedb422f4b'
down_revision: Union[str, None] = '23c14cd0373a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NOTE: autogenerate wanted to drop+recreate ix_document_chunks_embedding_hnsw
    # here -- that's a false positive. It's created via a raw `op.execute(...)`
    # in the initial migration (SQLAlchemy's Vector/HNSW support isn't
    # reflectable the same way as a plain Index), so autogenerate's diff
    # against declarative metadata doesn't see it and assumes it's extraneous.
    # Left out deliberately; see storage/migrations/versions/23c14cd0373a_*.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_column('documents', 'content_hash')
    # ### end Alembic commands ###
