#!/usr/bin/env python3
"""Retrieval evaluation harness.

Measures retrieval quality against `data/eval/queries.jsonl` -- 36
hand-written questions (deliberately phrased *differently* from the KB
entries themselves, one per intent in the sample dataset, so this isn't
just checking that the retriever can find a chunk it's already looking at
verbatim) each labeled with the category the retriever should surface.

Reports Hit@K (did the expected category appear anywhere in the top-K
results?), Mean Reciprocal Rank, and per-query retrieval latency, then
writes a Markdown report to docs/evaluation.md.

Assumes the pipeline has already been run (`rag-support pipeline` or
`make pipeline`) so the database has embedded chunks to search. Uses
whatever EMBEDDING_PROVIDER is configured -- run it once per tier
(offline/local/openai) to compare retrieval quality across them; see the
comparison table this script prints instructions for at the bottom of the
generated report.
"""

from __future__ import annotations

import json
import time
from pathlib import Path
from statistics import mean

from rag_support.config import get_settings
from rag_support.embeddings.factory import get_embedding_provider
from rag_support.rag.retriever import Retriever
from rag_support.storage.db import session_scope

_PROJECT_ROOT = Path(__file__).resolve().parent.parent
EVAL_SET_PATH = _PROJECT_ROOT / "data" / "eval" / "queries.jsonl"
REPORT_PATH = _PROJECT_ROOT / "docs" / "evaluation.md"


def load_eval_set() -> list[dict]:
    with EVAL_SET_PATH.open(encoding="utf-8") as f:
        return [json.loads(line) for line in f if line.strip()]


def run_evaluation(top_k: int = 4) -> tuple[str, list[dict]]:
    settings = get_settings()
    embedder = get_embedding_provider(settings)
    retriever = Retriever(embedder, default_top_k=top_k)
    eval_set = load_eval_set()

    rows: list[dict] = []
    with session_scope() as session:
        for item in eval_set:
            start = time.perf_counter()
            results = retriever.retrieve(session, item["query"], top_k=top_k)
            latency_ms = (time.perf_counter() - start) * 1000

            categories = [r.category for r in results]
            hit = item["expected_category"] in categories
            rank = categories.index(item["expected_category"]) + 1 if hit else None

            rows.append(
                {
                    "query": item["query"],
                    "expected_category": item["expected_category"],
                    "top_category": categories[0] if categories else None,
                    "hit": hit,
                    "rank": rank,
                    "latency_ms": round(latency_ms, 2),
                }
            )

    return embedder.name, rows


def summarize(rows: list[dict], top_k: int) -> dict:
    return {
        "hit_at_k": mean(1.0 if r["hit"] else 0.0 for r in rows),
        "mrr": mean((1.0 / r["rank"]) if r["hit"] else 0.0 for r in rows),
        "avg_latency_ms": mean(r["latency_ms"] for r in rows),
        "top_k": top_k,
        "n": len(rows),
    }


def write_report(provider_name: str, rows: list[dict], summary: dict) -> None:
    lines = [
        "# Retrieval evaluation",
        "",
        "Generated by `scripts/evaluate.py` against `data/eval/queries.jsonl` "
        f"({summary['n']} hand-written, held-out queries -- see that script's "
        "docstring for why they're deliberately not copies of the KB text).",
        "",
        f"- **Embedding provider**: `{provider_name}`",
        f"- **Hit@{summary['top_k']}** (expected category present in the top-{summary['top_k']} results): "
        f"{summary['hit_at_k']:.1%}",
        f"- **MRR** (mean reciprocal rank of the expected category): {summary['mrr']:.3f}",
        f"- **Avg retrieval latency**: {summary['avg_latency_ms']:.1f} ms",
        "",
        "| Query | Expected | Top result | Hit | Rank | Latency (ms) |",
        "|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| {r['query']} | {r['expected_category']} | {r['top_category']} | "
            f"{'yes' if r['hit'] else 'no'} | {r['rank'] or '-'} | {r['latency_ms']} |"
        )
    lines += [
        "",
        "## Reproducing / comparing providers",
        "",
        "This report reflects whichever `EMBEDDING_PROVIDER` was active when it was "
        "generated (see the heading above). To compare tiers, re-run with each one "
        "configured -- results will overwrite this file, so copy it aside if you want "
        "to keep more than one:",
        "",
        "```bash",
        "EMBEDDING_PROVIDER=offline python scripts/evaluate.py",
        "EMBEDDING_PROVIDER=local  python scripts/evaluate.py   # needs the local-ml extra",
        "EMBEDDING_PROVIDER=openai python scripts/evaluate.py   # needs OPENAI_API_KEY",
        "```",
        "",
    ]
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {REPORT_PATH}")


def main() -> None:
    provider_name, rows = run_evaluation()
    summary = summarize(rows, top_k=get_settings().top_k)
    print(
        f"provider={provider_name} hit@{summary['top_k']}={summary['hit_at_k']:.1%} "
        f"mrr={summary['mrr']:.3f} avg_latency_ms={summary['avg_latency_ms']:.1f}"
    )
    write_report(provider_name, rows, summary)


if __name__ == "__main__":
    main()
